// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef importui_h
#define importui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>
extern void cb_ImportDrawMode(Fl_Choice*, void*);
#include <FL/Fl_Spinner.H>
extern void cb_ImportZoom(Fl_Spinner*, void*);
#include <FL/Fl_Return_Button.H>
extern void cb_ImportOkay(Fl_Return_Button*, void*);
#include <FL/Fl_Button.H>
extern void cb_ImportCancel(Fl_Button*, void*);
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Value_Output.H>
extern void cb_ImportDepthChoice(Fl_Choice*, void*);
#include <FL/Fl_Check_Button.H>
extern void cb_ImportDither(Fl_Check_Button*, void*);
extern void cb_ImportQuantChoice(Fl_Choice*, void*);
extern void cb_ImportUpdate(Fl_Check_Button*, void*);
#include <FL/Fl_Value_Input.H>
extern void cb_ImportUpdateV(Fl_Value_Input*, void*);
extern void cb_ImportSetColorKey(Fl_Button*, void*);
extern void cb_ImportColorPick(Fl_Button*, void*);
#include <FL/Fl_Box.H>
extern void cb_ColorAdjToggle(Fl_Check_Button*, void*);
#include <FL/Fl_Value_Slider.H>
extern void cb_GeneralColAdj(Fl_Value_Slider*, long);
extern void cb_BlendColAdj(Fl_Value_Slider*, long);
extern void cb_ImportChanInv(Fl_Check_Button*, void*);

class ImportUI : public Fl_Double_Window {
  void _ImportUI();
public:
  ImportUI(int X, int Y, int W, int H, const char *L = 0);
  ImportUI(int W, int H, const char *L = 0);
  ImportUI();
  Fl_Scroll *preview;
  Fl_Choice *drawMode;
  static Fl_Menu_Item menu_drawMode[];
  Fl_Spinner *zoomValue;
  Fl_Return_Button *okayButton;
  Fl_Value_Output *srcDepth;
  Fl_Choice *depthChoice;
  static Fl_Menu_Item menu_depthChoice[];
  Fl_Check_Button *ditherToggle;
  Fl_Choice *quantizeMode;
  static Fl_Menu_Item menu_quantizeMode[];
  Fl_Value_Output *vmWidth;
  Fl_Group *stpOptions;
  Fl_Check_Button *stpNonBlack;
  Fl_Check_Button *stpBlack;
  Fl_Check_Button *stpNormal;
  Fl_Check_Button *stpAlpha;
  Fl_Group *alphaCtrls;
  Fl_Value_Input *alphaValue;
  Fl_Value_Input *stpAlphaValue;
  Fl_Check_Button *colorKey;
  Fl_Group *colorKeyCtrls;
  Fl_Button *pickButton;
  Fl_Box *colorKeyBox;
  Fl_Check_Button *colorAdjToggle;
  Fl_Value_Slider *generalAdj[3];
  Fl_Value_Slider *blendAdj[3];
  Fl_Check_Button *invertChan[3];
};
#endif
